name: C/C++ CI

on:
  push:
    branches: [ C++17 ]
  pull_request:
    branches: [ C++17 ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
        submodules: true
    - name: make
      run: make
    - name: make test
      run: make test
